// 侧边栏
export const TOGGLE_MAIN_SLIDE_BOX = 'SHOW_MAIN_SLIDE_BOX';
export const TOGGLE_SEARCH_SLIDE_BOX = 'TOGGLE_SEARCH_SLIDE_BOX';
export const TOGGLE_SUGGESTIONS = 'TOGGLE_SUGGESTIONS';

// 当前拥有的搜索引擎
export const SET_ALL_SEARCH_ENGINES = 'SET_ALL_SEARCH_ENGINES';
export const ADD_SEARCH_ENGINE = 'ADD_SEARCH_ENGINE';
export const DELETE_SEARCH_ENGINE = 'DELETE_SERCH_ENGINE';

// 当前选中的搜索引擎
export const SET_CURRENT_SEARCH_ENGINE = 'SET_CURRENT_SEARCH_ENGINE';

// 当前的用户搜索列表
export const SET_CUSTOM_SEARCH_ENGINES = 'SET_CUSTOM_SEARCH_ENGINES';

// 当前壁纸的信息
export const SET_CURRENT_BG = 'SET_CURRENT_BG';