// 视图层
export const TOGGLE_MAIN_SLIDE_BOX = 'SHOW_MAIN_SLIDE_BOX';
export const TOGGLE_SEARCH_SLIDE_BOX = 'TOGGLE_SEARCH_SLIDE_BOX';
export const TOGGLE_SUGGESTIONS = 'TOGGLE_SUGGESTIONS';
export const TOGGLE_SETTING = 'TOGGLE_SETTING';
export const TOGGLE_POPUP_MENU = 'TOGGLE_POPUP_MENU';
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';
export const CHANGE_CURRENT_DISTANCE = 'CHANGE_CURRENT_DISTANCE';

// 当前拥有的搜索引擎
export const SET_ALL_SEARCH_ENGINES = 'SET_ALL_SEARCH_ENGINES';
export const ADD_SEARCH_ENGINE = 'ADD_SEARCH_ENGINE';
export const DELETE_SEARCH_ENGINE = 'DELETE_SERCH_ENGINE';

// 当前选中的搜索引擎
export const SET_CURRENT_SEARCH_ENGINE = 'SET_CURRENT_SEARCH_ENGINE';

// 当前的用户搜索列表
export const SET_CUSTOM_SEARCH_ENGINES = 'SET_CUSTOM_SEARCH_ENGINES';

// 当前壁纸的信息
export const SET_CURRENT_BG = 'SET_CURRENT_BG';

// 当前拥有的网站
export const SET_CURRENT_SITES = 'SET_CURRENT_SITES';
export const ADD_SITE = 'ADD_SITE';
export const DELETE_SITE = 'DELETE_SITE';

// 当前网站设置
export const SET_CURRENT_SETTING = 'SET_CURRENT_SETTING';
export const UPDATE_CURRENT_SETTING = 'UPDATE_CURRENT_SETTING';

// 网站初始化
export const IS_FIRST_VISITED_SEARCH_SLIDE_BOX = 'IS_FIRST_VISITED_SEARCH_SLIDE_BOX';